[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "gpam_training"
author = "João Robson"
classifiers = ["License :: OSI Approved :: Apache Software License"]

